apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go-app
  labels:
    app: demo-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-go-app
  template:
    metadata:
      labels:
        app: demo-go-app
    spec:
      containers:
      - name: app
        image: gcr.io/PROJECT_ID/demo-go-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-go-app-service
  labels:
    app: demo-go-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-go-app