apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go-app
  namespace: default
  labels:
    app: demo-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-go-app
  template:
    metadata:
      labels:
        app: demo-go-app
    spec:
      containers:
      - name: demo-go-app
        image: gcr.io/idv-dev-0/demo-go-app:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: demo-go-app-service
  namespace: default
  labels:
    app: demo-go-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demo-go-app